indent                      = "\t"
min_empty_lines             = 0
max_empty_lines             = 2
max_use_tree_len            = 75
max_array_expr_len          = 80
max_chain_len               = 50
max_inline_tuple_struct_len = 80
