[package]
name    = "rustidy-print"
version = "0.1.0"
edition = "2024"

[dependencies]

# Workspace
rustidy-macros = { workspace = true }
rustidy-util   = { workspace = true }

[lints]
workspace = true
